name: eddl
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - cmake>=3.9.2
  - eigen>=3.3.7
  - zlib=1.2.*
  - protobuf=3.11.*
  - cudatoolkit
  - gtest
  - graphviz  # Build & Run
  - wget
  - doxygen  # Docs
  - python
  - pip
  - pip:
    - sphinx==3.0.3
    - sphinx_rtd_theme==0.4.3
    - sphinx-tabs==1.1.13
    - breathe==4.16.0